### ISSUE TITLE
Perform more specific check for inaccessible gateway links

### ISSUE THREAD

**Issue by hancush** [opencivicdata/python-legistar-scraper#110]
Recently, a huge number of public bills were marked as private because their gateway links could not be accessed: https://github.com/datamade/scrapers-us-municipal/issues/55#issuecomment-663003236.

Per @fgregg:

> it would be good to do a stricter check, if possible, that we are getting the kind of message we expect for private pages

One way to do that would be to update `legislation_detail_url` to check the response for a `200` status code and the page text for `This record is currently unavailable.`

https://github.com/opencivicdata/python-legistar-scraper/blob/b9267cbe5cc39823a6b883de5a122014d969b01a/legistar/bills.py#L450-L463

**Comment by hancush** [comment]
<img width="1440" alt="Screen Shot 2020-07-23 at 8 28 30 AM" src="https://user-images.githubusercontent.com/12176173/88291889-84145900-ccbe-11ea-99c7-055e337e1f7a.png">

**Comment by fgregg** [comment]
i would do one of two things

- stick with the head method and check that the response is either at 302 or 200 and fail otherwise
- start with the head method, and the response is not a 302, then make the full request and check content.

we should avoid making the full request for every bill, because that's add a lot of load and slow things down.

**Comment by hancush** [comment]
Great thought, @fgregg. For Metro, there are about 2k bills that should be private, so that's 2k additional requests per full scrape. I think I lean check for 302, fail otherwise!
