### ISSUE TITLE
`event['Meeting Details']` not always accurate

### ISSUE THREAD

**Issue by fatima3558** [opencivicdata/python-legistar-scraper#115]
Some legistar sites, such as [Phoenix, AZ](https://phoenix.legistar.com/Calendar.aspx) name their meeting information columns simply 'Details' (as opposed to 'Meeting Details') in the scraped tables.

We should update scraper code to account for this difference.

This is the code that triggered an error for the Phoneix, AZ legistar instance scrape:

https://github.com/opencivicdata/python-legistar-scraper/blob/fe43fd455883120843dc8f83625eb625de6021b1/legistar/events.py#L114-L117

**Comment by fgregg** [comment]
great bug report!

so it has been our practice to handle the site specific attributes by setting them as class attributes, i.e.

https://github.com/opencivicdata/python-legistar-scraper/blob/fe43fd455883120843dc8f83625eb625de6021b1/legistar/base.py#L77

This is not really quite the right thing to do, because these attributes should really belong to instances.

Please create a PR, that adds the name of the meeting_detail key to the init of the webapiscraper.

**Comment by fgregg** [comment]
you'll also need to pass the unused kwargs and args to a super() init

**Comment by fatima3558** [comment]
addressed in PR #116
