### ISSUE TITLE
Events: Look at all endpoints

### ISSUE THREAD

**Issue by reginafcompton** [opencivicdata/python-legistar-scraper#30]
The events scraper should hit all related endpoints, e.g., event agenda items - that is, if an event agenda item changes, but the event does not change, then the scraper should catch the change.

**Comment by fgregg** [comment]
I investigated this a little tonight, and the issue is that *attachment* are nowhere in the API. So, we have no way of using the API to figure out which events had updated attachments. 

Given that, I adjusted legistar-scraper and the lametro and chicago scrapers to scrape **all** events every hour.
